version: '3'

includes:
  glad:
    taskfile: ./cmd/glad/Taskfile.yml
    dir: .

tasks:
  default:
    desc: 'List all available tasks'
    cmd: task --list-all

  # Global tasks
  test:
    desc: 'Run all tests'
    cmds:
      - go test ./...

  test:verbose:
    desc: 'Run all tests with verbose output'
    cmds:
      - go test -v ./...

  test:coverage:
    desc: 'Run tests with coverage report'
    cmds:
      - go test -v -cover ./...
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - echo 'Coverage report generated - coverage.html'

  fmt:
    desc: 'Format all Go code'
    cmds:
      - go fmt ./...

  lint:
    desc: 'Run Go linter'
    cmds:
      - echo 'Running go vet...'
      - go vet ./...

  clean:
    desc: 'Clean build artifacts'
    cmds:
      - rm -rf .bin/
      - echo 'Cleaned build artifacts'

  # Continue AI tasks
  continue:refresh-token:
    desc: 'Refresh msg ai api-token'
    cmds:
      - scripts/continue-refresh-token.sh

  # Development workflow shortcuts
  dev:full-test:
    desc: 'Run full development test cycle'
    deps: [fmt, lint, test]

  dev:quick-test:
    desc: 'Quick development test'
    deps: [fmt, test]
